# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pin',
            field=models.BooleanField(default=True),
        ),
    ]
